[METADATA]
version = "1.0"

[[VALIDATORS]]
public_key = "nHUdwCKijaKAD8NUUR8sKPV3Kj9F2EJW3E5Lsb62yod2T7kR2y9F"
network = "main"
owner_country = "US"
server_country = "US"
unl = "https://vl.ripple.com"
